/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx}", "./src/types/**/*.json"],
  safelist: [
    "md:col-span-4",
    "md:col-span-8",
    "md:col-span-12",
    "md:row-span-1",
    "md:row-span-2",
    "animate-[spin_70s_linear_infinite_reverse]",
    "animate-[spin_90s_linear_infinite]",
    "animate-planned-pulse",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "terminal-green": "var(--terminal-green)",
        "neon-accent": "var(--neon-accent)",
        "encryption-purple": "#4F46E5",
        "surface-base": "var(--stitch-surface-base)",
        "surface-elevated": "var(--stitch-surface-elevated)",
        "surface-container-lowest": "var(--stitch-surface-container-lowest)",
        "surface-variant": "var(--stitch-surface-variant)",
        "border-subtle": "var(--stitch-border-subtle)",
        "on-surface": "var(--stitch-on-surface)",
        "on-surface-variant": "var(--stitch-on-surface-variant)",
        "mt-primary": "var(--mt-primary)",
        "mt-primary-fixed": "var(--mt-primary-fixed)",
        "mt-primary-fixed-dim": "var(--mt-primary-fixed-dim)",
        "mt-primary-container": "var(--mt-primary-container)",
        "mt-on-primary": "var(--mt-on-primary)",
        "mt-on-primary-container": "var(--mt-on-primary-container)",
        "mt-surface": "var(--mt-surface)",
        "mt-surface-dim": "var(--mt-surface-dim)",
        "mt-surface-bright": "var(--mt-surface-bright)",
        "mt-surface-tint": "var(--mt-surface-tint)",
        "mt-surface-container": "var(--mt-surface-container)",
        "mt-surface-container-low": "var(--mt-surface-container-low)",
        "mt-surface-container-high": "var(--mt-surface-container-high)",
        "mt-surface-container-highest": "var(--mt-surface-container-highest)",
        "mt-surface-container-lowest": "var(--mt-surface-container-lowest)",
        "mt-surface-variant": "var(--mt-surface-variant)",
        "mt-on-surface": "var(--mt-on-surface)",
        "mt-on-surface-variant": "var(--mt-on-surface-variant)",
        "mt-on-background": "var(--mt-on-background)",
        "mt-background": "var(--mt-background)",
        "mt-outline": "var(--mt-outline)",
        "mt-outline-variant": "var(--mt-outline-variant)",
        "mt-secondary": "var(--mt-secondary)",
        "mt-secondary-container": "var(--mt-secondary-container)",
        "mt-on-secondary": "var(--mt-on-secondary)",
        "mt-on-secondary-container": "var(--mt-on-secondary-container)",
        "mt-tertiary": "var(--mt-tertiary)",
        "mt-tertiary-container": "var(--mt-tertiary-container)",
        "mt-on-tertiary": "var(--mt-on-tertiary)",
        "mt-on-tertiary-container": "var(--mt-on-tertiary-container)",
        "mt-error": "var(--mt-error)",
        "mt-error-container": "var(--mt-error-container)",
        "mt-on-error": "var(--mt-on-error)",
        "mt-on-error-container": "var(--mt-on-error-container)",
        "mt-inverse-surface": "var(--mt-inverse-surface)",
        "mt-inverse-on-surface": "var(--mt-inverse-on-surface)",
        "mt-inverse-primary": "var(--mt-inverse-primary)",
        "mt-liquid-mint": "var(--mt-liquid-mint)",
        "mt-ledger-white": "var(--mt-ledger-white)",
        "mt-glass-border": "var(--mt-glass-border)",
        "mt-pure-black": "var(--mt-pure-black)",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        pj:['"PIXymbols Very Loose W01 Reg"', 'sans-serif'],
        body: ['var(--font-hanken-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['var(--font-hanken-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['var(--font-hanken-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'helvetica-97-condensed-oblique': ['"Helvetica Neue LT Pro 97 Black Condensed Oblique"', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
        label: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
        headline: ['var(--font-hanken-grotesk)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      letterSpacing: {
        headline: "0.08em",
        label: "0.05em",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },

    },
  },
  plugins: [require("tailwindcss-animate")],
};
