import { ReactNode } from "react";
import { HeadComponent } from "./head-component";
import AuthWrapper from "./auth-wrapper";
import React from "react";

interface LayoutProps {
  flexDirection?: "row" | "col";
  justify?: "start" | "end" | "center" | "between" | "around" | "evenly";
  align?: "start" | "end" | "center" | "baseline" | "stretch";
  gap?: number;
  background?: string; // Accept background as an optional prop
}

interface PageLayoutProps extends LayoutProps {
  children: ReactNode;
  title?: string;
  description?: string;
  requireAuth?: boolean;
  image?: string; // Optional custom image for social sharing
  url?: string; // Optional custom URL for social sharing
}

export const PageLayout: React.FC<PageLayoutProps> = ({
  children,
  title = "Sizland App",
  description = "Generated by @rainbow-me/rainbowkit",
  flexDirection = "col",
  justify = "start",
  align = "center",
  gap = 8,
  background, // Destructure background from props
  requireAuth = true, // Default to requiring authentication
  image, // Optional custom image
  url, // Optional custom URL
}) => {
  const content = (
    <>
      <HeadComponent title={title} description={description} image={image} url={url} />
      <MainContainer
        flexDirection={flexDirection}
        justify={justify}
        align={align}
        gap={gap}
        background={background} // Pass background to MainContainer
      >
        {children}
      </MainContainer>
    </>
  );

  // Wrap with AuthWrapper if authentication is required
  if (requireAuth) {
    return <AuthWrapper>{content}</AuthWrapper>;
  }

  return content;
};

const MainContainer: React.FC<LayoutProps & { children: React.ReactNode; background?: string }> = ({
  children,
  flexDirection = "col",
  justify = "start",
  align = "center",
  gap = 8,
  background, // Accept background as an optional prop
}) => {
  const justifyClass = {
    start: "justify-start",
    end: "justify-end",
    center: "justify-center",
    between: "justify-between",
    around: "justify-around",
    evenly: "justify-evenly",
  }[justify];

  const alignClass = {
    start: "items-start",
    end: "items-end",
    center: "items-center",
    baseline: "items-baseline",
    stretch: "items-stretch",
  }[align];

  const flexDirectionClass = {
    row: "flex-row",
    col: "flex-col",
  }[flexDirection];

  const gapClass = {
    1: "gap-1",
    2: "gap-2",
    3: "gap-3",
    4: "gap-4",
    5: "gap-5",
    6: "gap-6",
    7: "gap-7",
    8: "gap-8",
    9: "gap-9",
    10: "gap-10",
    12: "gap-12",
    16: "gap-16",
    20: "gap-20",
    24: "gap-24",
    32: "gap-32",
  }[gap] || "gap-8";

  return (
    <main
      className={`min-h-[100vh] p-8 flex ${flexDirectionClass} ${justifyClass} ${alignClass} ${gapClass} py-32`}
      style={{ background: background }} // Apply the background style conditionally
    >
      {children}
    </main>
  );
};
